//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://159.65.237.98:8182/application.wadl")]
        public string ApplicationUrl {
            get {
                return ((string)(this["ApplicationUrl"]));
            }
            set {
                this["ApplicationUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://159.65.237.98:8182/healthcheck")]
        public string HealthcheckUrl {
            get {
                return ((string)(this["HealthcheckUrl"]));
            }
            set {
                this["HealthcheckUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://159.65.237.98:8182/api/v1/contacts/")]
        public string ContactsUrl {
            get {
                return ((string)(this["ContactsUrl"]));
            }
            set {
                this["ContactsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Content-type")]
        public string ContentType {
            get {
                return ((string)(this["ContentType"]));
            }
            set {
                this["ContentType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("application/json")]
        public string ContentTypeValue {
            get {
                return ((string)(this["ContentTypeValue"]));
            }
            set {
                this["ContentTypeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("firstName")]
        public string JsonFirstNameFieldName {
            get {
                return ((string)(this["JsonFirstNameFieldName"]));
            }
            set {
                this["JsonFirstNameFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lastName")]
        public string JsonLastNameFieldName {
            get {
                return ((string)(this["JsonLastNameFieldName"]));
            }
            set {
                this["JsonLastNameFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("email")]
        public string JsonEmalilFieldName {
            get {
                return ((string)(this["JsonEmalilFieldName"]));
            }
            set {
                this["JsonEmalilFieldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://159.65.237.98:80")]
        public string UiUrl {
            get {
                return ((string)(this["UiUrl"]));
            }
            set {
                this["UiUrl"] = value;
            }
        }
    }
}
